//! `xtask gen-skill` / `xtask check-skill-drift` — keep the bundled skill's
//! command reference in step with the CLI (iter-212 Theme C).
//!
//! `crates/ff-rdp-cli/skills/ff-rdp-debug/SKILL.md` is mostly hand-written
//! prose — the symptom router, the playbook index, the output contract — and
//! should stay that way. What must *not* stay hand-written is the part that
//! restates the CLI: the one-line description, the quick start, the command
//! groups, and the `--ref` / `--query` / `--with-page` idioms. Those are
//! generated by `ff_rdp_cli::commands::skill_doc` and spliced into the region
//! between the two marker comments.
//!
//! The generator lives in the CLI (it shares its tables with the home view),
//! and the CLI is a binary crate, so this module obtains the generated text by
//! running `ff-rdp skill-doc` rather than by linking it. `FF_RDP_BIN` short-
//! circuits the `cargo run` when a built binary is already at hand.

use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result, bail};
use clap::Args as ClapArgs;

/// HTML comment that opens the generated region. Must match
/// `ff_rdp_cli::commands::skill_doc::BLOCK_BEGIN`; a mismatch surfaces
/// immediately as "markers not found", never as a silent no-op.
const BLOCK_BEGIN: &str = "<!-- ff-rdp:generated:begin -->";
/// HTML comment that closes the generated region.
const BLOCK_END: &str = "<!-- ff-rdp:generated:end -->";

/// Path of the committed skill file, relative to the workspace root.
const SKILL_PATH: &str = "crates/ff-rdp-cli/skills/ff-rdp-debug/SKILL.md";

#[derive(ClapArgs)]
pub struct GenArgs {
    /// Skill file to rewrite (defaults to the bundled ff-rdp-debug skill)
    #[arg(long, value_name = "PATH")]
    pub skill: Option<PathBuf>,
}

#[derive(ClapArgs)]
pub struct CheckArgs {
    /// Skill file to check (defaults to the bundled ff-rdp-debug skill)
    #[arg(long, value_name = "PATH")]
    pub skill: Option<PathBuf>,
}

/// The workspace root, found by walking up from this crate's manifest dir.
fn workspace_root() -> PathBuf {
    let mut dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    while dir.pop() {
        if dir.join("Cargo.lock").exists() {
            return dir;
        }
    }
    PathBuf::from(".")
}

fn skill_file(explicit: Option<&Path>) -> PathBuf {
    explicit.map_or_else(|| workspace_root().join(SKILL_PATH), Path::to_path_buf)
}

/// Ask the CLI for the generated block.
///
/// Uses `FF_RDP_BIN` when set (CI and the live sweep both already have a built
/// binary), otherwise `cargo run -q -p ff-rdp-cli`. Either way the generator is
/// the one compiled from the tree under test, never a stale binary from PATH —
/// the same rule `tools/lint-dogfood-script.sh` enforces for dogfood scripts,
/// and for the same reason: a stale binary certifies a build nobody is running.
fn generated_block() -> Result<String> {
    let output = if let Some(bin) = std::env::var_os("FF_RDP_BIN") {
        Command::new(&bin)
            .arg("skill-doc")
            .output()
            .with_context(|| format!("failed to run {bin:?} skill-doc"))?
    } else {
        Command::new(std::env::var("CARGO").unwrap_or_else(|_| "cargo".to_owned()))
            .args(["run", "-q", "-p", "ff-rdp-cli", "--", "skill-doc"])
            .current_dir(workspace_root())
            .output()
            .context("failed to run `cargo run -q -p ff-rdp-cli -- skill-doc`")?
    };
    if !output.status.success() {
        bail!(
            "the skill-doc generator exited {}: {}",
            output.status,
            String::from_utf8_lossy(&output.stderr).trim()
        );
    }
    String::from_utf8(output.stdout).context("the skill-doc generator emitted non-UTF-8")
}

/// Extract the generated region of `existing`, markers included.
///
/// `None` when a marker is missing or they appear out of order — the caller
/// reports that as a hard failure rather than guessing where the block goes.
pub fn extract_block(existing: &str) -> Option<&str> {
    let start = existing.find(BLOCK_BEGIN)?;
    let end = existing.find(BLOCK_END)?;
    if end < start {
        return None;
    }
    Some(&existing[start..end + BLOCK_END.len()])
}

/// Replace the generated region of `existing` with `generated`.
///
/// Never appends to a file that does not declare where the block goes:
/// silently bolting a generated section onto the end of a hand-written skill
/// is worse than refusing.
pub fn splice_block(existing: &str, generated: &str) -> Option<String> {
    let start = existing.find(BLOCK_BEGIN)?;
    let end = existing.find(BLOCK_END)?;
    if end < start {
        return None;
    }
    let mut out = String::with_capacity(existing.len() + generated.len());
    out.push_str(&existing[..start]);
    // `generated` carries a trailing newline after its end marker and the tail
    // of the file already begins with one; trimming ours keeps the splice
    // idempotent instead of growing a blank line per regeneration.
    out.push_str(generated.trim_end_matches('\n'));
    out.push_str(&existing[end + BLOCK_END.len()..]);
    Some(out)
}

/// Whether the committed file's generated region already equals `generated`.
///
/// `Ok(())` when it matches; `Err(report)` with a first-differing-line report
/// otherwise. Separated from all I/O so the drift verdict is unit-testable.
pub fn drift_report(existing: &str, generated: &str) -> Result<(), String> {
    let Some(committed) = extract_block(existing) else {
        return Err(format!(
            "the generated markers are missing (or reversed).\n\
             Expected a region delimited by:\n  {BLOCK_BEGIN}\n  {BLOCK_END}"
        ));
    };
    let generated = generated.trim_end_matches('\n');
    if committed == generated {
        return Ok(());
    }
    let first_diff = committed
        .lines()
        .zip(generated.lines())
        .position(|(a, b)| a != b);
    let detail = match first_diff {
        Some(i) => {
            let committed_line = committed.lines().nth(i).unwrap_or("");
            let generated_line = generated.lines().nth(i).unwrap_or("");
            format!(
                "first difference at line {} of the generated region:\n  committed: {committed_line}\n  generated: {generated_line}",
                i + 1
            )
        }
        None => format!(
            "the regions have different lengths ({} committed lines vs {} generated)",
            committed.lines().count(),
            generated.lines().count()
        ),
    };
    Err(detail)
}

pub fn run_gen(args: GenArgs) -> Result<()> {
    let path = skill_file(args.skill.as_deref());
    let existing = std::fs::read_to_string(&path)
        .with_context(|| format!("failed to read {}", path.display()))?;
    let generated = generated_block()?;
    let Some(updated) = splice_block(&existing, &generated) else {
        bail!(
            "{} has no generated region: add the markers\n  {BLOCK_BEGIN}\n  {BLOCK_END}\n\
             around the section `xtask gen-skill` should own.",
            path.display()
        );
    };
    if updated == existing {
        println!("gen-skill: {} already current", path.display());
        return Ok(());
    }
    std::fs::write(&path, updated)
        .with_context(|| format!("failed to write {}", path.display()))?;
    println!(
        "gen-skill: rewrote the generated region of {}",
        path.display()
    );
    Ok(())
}

pub fn run_check(args: CheckArgs) -> Result<()> {
    let path = skill_file(args.skill.as_deref());
    let existing = std::fs::read_to_string(&path)
        .with_context(|| format!("failed to read {}", path.display()))?;
    let generated = generated_block()?;
    match drift_report(&existing, &generated) {
        Ok(()) => {
            println!("check-skill-drift: {} is current", path.display());
            Ok(())
        }
        Err(detail) => bail!(
            "{} is stale: its generated region no longer matches \
             crates/ff-rdp-cli/src/commands/skill_doc.rs.\n{detail}\n\
             fix: cargo run -p xtask -- gen-skill",
            path.display()
        ),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn file(body: &str) -> String {
        format!("# Skill\n\nprose\n\n{BLOCK_BEGIN}\n{body}\n{BLOCK_END}\n\nmore prose\n")
    }

    fn block(body: &str) -> String {
        format!("{BLOCK_BEGIN}\n{body}\n{BLOCK_END}\n")
    }

    /// AC `check_skill_drift_fails_on_stale_skill`: editing the committed
    /// generated region by one line makes the check fail, and the failure
    /// names the line that moved.
    #[test]
    fn unit_212_one_edited_line_is_drift() {
        let generated = block("| Group | Use it for | Commands |\n| Act | click | `click` |");
        let current = file("| Group | Use it for | Commands |\n| Act | click | `click` |");
        assert!(drift_report(&current, &generated).is_ok());

        let stale = file("| Group | Use it for | Commands |\n| Act | click | `clik` |");
        let report = drift_report(&stale, &generated).expect_err("one edited line must be drift");
        assert!(report.contains("first difference at line 3"), "{report}");
        assert!(report.contains("clik"), "{report}");
    }

    /// A line *removed* from the committed region is drift too — the
    /// zip-based scan would otherwise walk off the end and see no difference.
    #[test]
    fn unit_212_a_removed_line_is_drift() {
        let generated = block("one\ntwo\nthree");
        let stale = file("one\ntwo");
        let report = drift_report(&stale, &generated).expect_err("a dropped line must be drift");
        assert!(report.contains("different lengths"), "{report}");
    }

    /// Hand-written prose outside the markers is *not* drift: the whole point
    /// of the region is that the rest of the skill stays editable.
    #[test]
    fn unit_212_prose_outside_the_markers_is_not_drift() {
        let generated = block("body");
        let mut edited = file("body");
        edited = edited.replace("more prose", "completely rewritten prose, by hand");
        assert!(drift_report(&edited, &generated).is_ok());
    }

    #[test]
    fn unit_212_missing_markers_are_reported_not_ignored() {
        let report = drift_report("no markers at all\n", &block("body"))
            .expect_err("a file without markers cannot be current");
        assert!(report.contains("markers are missing"), "{report}");
    }

    #[test]
    fn unit_212_splice_replaces_only_the_marked_region_and_is_idempotent() {
        let existing = file("old body");
        let generated = block("new body");
        let once = splice_block(&existing, &generated).expect("markers present");
        assert!(once.contains("new body"), "{once}");
        assert!(!once.contains("old body"), "{once}");
        assert!(once.contains("more prose"), "the tail must survive: {once}");
        let twice = splice_block(&once, &generated).expect("markers present");
        assert_eq!(once, twice, "splicing must not grow the file each run");
        assert!(drift_report(&once, &generated).is_ok());
    }

    #[test]
    fn unit_212_splice_refuses_a_file_with_no_region() {
        assert!(splice_block("nothing here\n", &block("body")).is_none());
        let reversed = format!("{BLOCK_END}\n{BLOCK_BEGIN}\n");
        assert!(splice_block(&reversed, &block("body")).is_none());
        assert!(extract_block(&reversed).is_none());
    }
}
